import { IconTrendingUp } from "@tabler/icons-react"

import { Badge } from "@/components/ui/badge"
import {
  Card,
  CardAction,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"

interface SectionCardsProps {
  totalGeneratedQueries: number;
  totalExecutedQueries: number;
}

export function SectionCards({ totalGeneratedQueries, totalExecutedQueries }: SectionCardsProps) {
  return (
    <div className="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card grid grid-cols-1 gap-4 px-4 *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs lg:px-6 @xl/main:grid-cols-2 @5xl/main:grid-cols-4">
      <Card className=" @container/card">
        <CardHeader>
          <CardDescription>Total Generated Queries</CardDescription>
          <CardTitle className="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">
            {totalGeneratedQueries}
          </CardTitle>
          <CardAction>
            <Badge variant="outline">
              <IconTrendingUp />
              N/A
            </Badge>
          </CardAction>
        </CardHeader>
        <CardFooter className="flex-col items-start gap-1.5 text-sm">
          <div className="line-clamp-1 flex gap-2 font-medium">
            All queries generated by AuraSQL
          </div>
          <div className="text-muted-foreground">
            Includes both executed and non-executed queries
          </div>
        </CardFooter>
      </Card>
      <Card className=" @container/card">
        <CardHeader>
          <CardDescription>Total Executed Queries</CardDescription>
          <CardTitle className="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">
            {totalExecutedQueries}
          </CardTitle>
          <CardAction>
            <Badge variant="outline">
              <IconTrendingUp />
              N/A
            </Badge>
          </CardAction>
        </CardHeader>
        <CardFooter className="flex-col items-start gap-1.5 text-sm">
          <div className="line-clamp-1 flex gap-2 font-medium">
            Queries successfully executed
          </div>
          <div className="text-muted-foreground">
            Subset of generated queries
          </div>
        </CardFooter>
      </Card>
    </div>
  )
}